# ðŸ‡»ðŸ‡³ Air configuration for hot reload
# ðŸ‡ºðŸ‡¸ Air configuration for hot reload

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary, can setup environment variables when run your app.
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "scripts"]
  # Watch these directories if you specified.
  include_dir = []
  # Exclude files.
  exclude_file = []
  # This log file places in your tmp_dir.
  log = "errors.log"
  # Poll files for changes instead of using filesystem events (useful on WSL)
  poll = false
  # Poll interval (defaults to 500ms in case poll is enabled)
  poll_interval = 0
  # Delay after each executions (s, ms, us, ns)
  delay = 1000
  # Stop running old binary when build errors occur.
  stop_on_error = false
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s"
  # Rerun binary or not
  rerun = false
  # Delay after each executions
  rerun_delay = 500
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = []

[log]
  # Show log time
  time = false
  # Only show main log (hide build log)
  main_only = false

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  # Clear screen on each rebuild
  clear_on_rebuild = false
  # Keep screen after each build
  keep_scroll = true

