server:
  port: "3000"
  host: "0.0.0.0"

database:
  host: "103.216.119.162"
  port: "5432"
  user: "qc_thuan_nhien_app"
  password: "TN@2026"
  dbname: "qc_thuan_nhien_db"
  sslmode: "disable"
  timezone: "Asia/Ho_Chi_Minh"

